---
title: "508 TOD San Diego"
author: "Ann Zhang"
date: "2022-09-12"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

# loading packages
```{r results='hide', warning= FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='hide', warning= FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(dplyr)

options(scipen=999)
options(tigris_class = "sf")

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#f0f9e8","#bae4bc","#7bccc4","#43a2ca","#0868ac")
```

```{r load_key, results='hide', warning = FALSE, eval = FALSE}
census_api_key("b3abcecc231fa30ccaa18cb5e854c30f1982fe3f", overwrite = TRUE, install = TRUE)
readRenviron("~/.Renviron")
```

```{r results='hide', warning= FALSE}
tracts09 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E","B02001_002E",
                        "B15001_050E","B15001_009E",
                        "B19013_001E","B25058_001E",
                        "B06012_002E"), 
          year=2009, state=06, county=073, 
          geometry=TRUE) %>%
  st_transform('ESRI:102411')

tracts19 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E","B02001_002E",
                        "B15001_050E","B15001_009E",
                        "B19013_001E","B25058_001E",
                        "B06012_002E"), 
          year=2019, state=06, county=073, 
          geometry=TRUE) %>%
  st_transform('ESRI:102411') 

```

```{r results='hide', warning= FALSE}
SD_Stops <- st_read("https://seshat.datasd.org/sde/transit_stops_gtfs/transit_stops_datasd.geojson") %>%
  filter(stop_agncy == "MTS")

SD_StopsRoutes <- st_read("https://gissd.sandag.org/rdw/rest/services/Transportation/GTFS_Transit/MapServer/2/query?where=1%3D1&outFields=*&outSR=4326&f=json") %>%
  filter(route_id == 510| route_id == 520| route_id == 530) %>%
  rename(stop_uid = stop_UID) %>%
  mutate(Line = case_when(route_id ==510 ~ "Blue Line",
                          route_id ==520 ~ "Orange Line",
                          route_id ==530 ~ "Green Line",))

SD_All <- left_join(SD_StopsRoutes, SD_Stops, by= c("stop_uid")) %>%
   dplyr::select(stop_name, Line, geometry, lat, lng)

SD_Trolley <- SD_All[!duplicated(SD_All$stop_name),] %>%
  st_as_sf(coords  = c("lng", "lat"),
           crs = "EPSG:4326") %>%
  st_transform('ESRI:102411')

```


```{r results='hide', warning= FALSE}
SD_Buffers <- 
  rbind(
    st_buffer(SD_Trolley$geometry, 805) %>%
      st_sf() %>%
      mutate(Legend = "Buffer") %>%
      dplyr::select(Legend),
    st_union(st_buffer(SD_Trolley$geometry, 805)) %>%
      st_sf() %>%
      mutate(Legend = "Unioned Buffer"))

buffer <- filter(SD_Buffers, Legend=="Unioned Buffer") %>%
  st_transform('ESRI:102411')

```

#Population

```{r results='hide', warning= FALSE}

Pop09_19 <- 
  rbind(
      tracts09 %>%
      filter(variable=="B25026_001") %>%
      mutate(year=2009), 
      tracts19 %>%
      filter(variable=="B25026_001") %>%
      mutate(year=2019) )

ggplot() +
  geom_sf(data = Pop09_19, aes(fill = q5(estimate), group=year), color=NA) +
    scale_fill_manual(values = palette5,
                    labels = qBr(Pop09_19, "estimate"),
                    name = "Popluation\n(Quintile Breaks)") +
    facet_wrap(~year) +
    labs(title = "Population in occupied housing", subtitle = "San Diego; 2009 vs. 2019") +
    mapTheme() + theme(plot.title = element_text(size=22)) +
    geom_sf(data=buffer, color="red", fill=NA)


```
# Rent

```{r results='hide', warning= FALSE}

Rent09_19 <- 
  rbind(
      tracts09 %>%
      filter(variable=="B25058_001") %>%
      mutate(year=2009),
      tracts19 %>%
      filter(variable=="B25058_001") %>%
      mutate(year=2019))

ggplot() +
  geom_sf(data = Rent09_19, aes(fill = q5(estimate), group=year), color=NA) +
    scale_fill_manual(values = palette5,
                    labels = qBr(Rent09_19, "estimate"),
                    name = "Rent ($ per month)\n(Quintile Breaks)") +
    facet_wrap(~year) +
    labs(title = "Rent", subtitle = "San Diego; 2009 vs. 2019") +
    mapTheme() + theme(plot.title = element_text(size=22)) +
    geom_sf(data=buffer, color="red", fill=NA)


```

#Household income
```{r results='hide', warning= FALSE}
HHinc09_19 <- 
  rbind(
      tracts09 %>%
      filter(variable=="B19013_001") %>%
      mutate(year=2009),
      tracts19 %>%
      filter(variable=="B19013_001") %>%
      mutate(year=2019))

ggplot() +
  geom_sf(data = HHinc09_19, aes(fill = q5(estimate), group=year), color=NA) +
    scale_fill_manual(values = palette5,
                    labels = qBr(HHinc09_19, "estimate"),
                    name = "Household Income ($)\n(Quintile Breaks)") +
    facet_wrap(~year) +
    labs(title = "Median Household Income in the past 12 months", subtitle = "San Diego; 2009 vs. 2019") +
    mapTheme() + theme(plot.title = element_text(size=22)) +
    geom_sf(data=buffer, color="red", fill=NA)

```

#Household income
```{r results='hide', warning= FALSE}
Pov09_19 <- 
  rbind(
      tracts09 %>%
      filter(variable=="B06012_002") %>%
      mutate(year=2009),
      tracts19 %>%
      filter(variable=="B06012_002") %>%
      mutate(year=2019))

ggplot() +
  geom_sf(data = Pov09_19, aes(fill = q5(estimate), group=year), color=NA) +
    scale_fill_manual(values = palette5,
                    labels = qBr(Pov09_19, "estimate"),
                    name = "Below 100% of the Poverty Level\n(Quintile Breaks)") +
    facet_wrap(~year) +
    labs(title = "Poverty", subtitle = "San Diego; 2009 vs. 2019") +
    mapTheme() + theme(plot.title = element_text(size=22)) +
    geom_sf(data=buffer, color="red", fill=NA)

```

```{r results='hide', warning= FALSE}
tracts09 <-
  tracts09 %>%
  dplyr::select( -NAME, -moe) %>%
  spread(variable, estimate) %>%
  st_transform('ESRI:102411') %>%
  rename(TotalPop = B25026_001, 
        Whites = B02001_002,
         FemaleBachelors = B15001_050, 
         MaleBachelors = B15001_009,
         MedHHInc = B19013_001, 
         MedRent = B25058_001,
         TotalPoverty = B06012_002) %>%
  dplyr::select(-starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009")

```


```{r results='hide', warning= FALSE}
tracts19 <-
  tracts19 %>%
  dplyr::select( -NAME, -moe) %>%
  spread(variable, estimate) %>%
  st_transform('ESRI:102411') %>%
  rename(TotalPop = B25026_001, 
         Whites = B02001_002,
         FemaleBachelors = B15001_050, 
         MaleBachelors = B15001_009,
         MedHHInc = B19013_001, 
         MedRent = B25058_001,
         TotalPoverty = B06012_002) %>%
  dplyr::select(-starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019")

allTracts <- rbind(tracts19,tracts09)
```

#San Diego Transit Stops

```{r results='hide', warning= FALSE}

ggplot() + 
  geom_sf(data=st_union(tracts19)) +
  geom_sf(data=SD_Trolley$geometry,
          aes(color = SD_Trolley$Line),
          show.legend = "point", size = 2) +
  scale_colour_manual(values = c("blue","green","orange")) +
  labs(title="Trolley Stops", 
       subtitle="San Diego, CA", 
       caption="Figure") +
  mapTheme()

```

```{r results='hide', warning= FALSE}

ggplot() +
  facet_wrap(~Legend) +
  geom_sf(data=SD_Buffers) +
  geom_sf(data=SD_Trolley, show.legend = "point") +
  mapTheme()

```

#joining buffers and tracts

```{r}

selection_SD1 <- tracts19 %>% 
  st_join(buffer, join = st_intersects) %>% 
  filter(!is.na(Legend)) %>% 
  dplyr::select(TotalPop) %>%
  mutate(Selection_Type = "Spatial Intersects")

```


#indicator maps
1. tables

```{r results='hide', warning= FALSE}
SDallTracts.group <- 
  rbind(
    st_centroid(allTracts)[buffer,] %>%
      st_drop_geometry() %>%
      left_join(allTracts) %>%
      st_sf() %>%
      mutate(TOD = "TOD"),
    
    st_centroid(allTracts)[buffer, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(allTracts) %>%
      st_sf() %>%
      mutate(TOD = "Non-TOD")) %>%
  mutate(MedRent.inf = ifelse(year == "2009", MedRent * 1.19, MedRent)) 

SDallTracts.Summary <- 
  st_drop_geometry(SDallTracts.group) %>%
  group_by(year, TOD) %>%
  summarize(Rent = mean(MedRent, na.rm = T),
            Population = mean(TotalPop, na.rm = T),
            Percent_White = mean(pctWhite, na.rm = T),
            Percent_Bach = mean(pctBachelors, na.rm = T),
            Percent_Poverty = mean(pctPoverty, na.rm = T))

kable(SDallTracts.Summary) %>%
  kable_styling() %>%
  footnote(general_title = "\n",
           general = "Table 2.2")


```



2. charts

```{r results='hide', warning= FALSE}
SDallTracts.Summary %>%
  gather(Variable, Value, -year, -TOD) %>%
  ggplot(aes(year, Value, fill = TOD)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~Variable, scales = "free", ncol=5) +
  scale_fill_manual(values = c("#bae4bc", "#0868ac")) +
  labs(title = "Indicator differences across time and space", subtitle = "San Diego, CA") +
  plotTheme() + theme(legend.position="bottom")
```
#Graduated Symbol Map

```{r results='hide', warning= FALSE}
BufferOnly <- filter(SD_Buffers, Legend == "Buffer") %>%
  st_transform('ESRI:102411') %>%
  tibble::rowid_to_column("ID")

SD_Station <- st_join(BufferOnly, tracts19, join = st_intersects) %>%
  dplyr::select(ID, Legend, GEOID, TotalPop, MedRent, geometry) %>%
  dplyr::group_by(ID) %>%
  summarize(pop=mean(TotalPop, na.rm = TRUE), rent=mean(MedRent, na.rm = TRUE))

ggplot() +
  geom_sf(data = tracts19) +
  geom_sf(data = st_centroid(SD_Station),
          pch = 21,
          aes(size = pop),
          fill = alpha("red", 0.7),
          col = "grey20") +
  labs(size = "Population") +
  scale_size(range = c(1, 5)) +
  mapTheme()
  
```

```{r results='hide', warning= FALSE}
ggplot() +
  geom_sf(data = tracts19) +
  geom_sf(data = st_centroid(SD_Station),
          pch = 21,
          aes(size = rent),
          fill = alpha("blue", 0.7),
          col = "grey20") +
  labs(size = "Rent") +
  scale_size(range = c(1, 5)) + 
  mapTheme()
```


```{r results='hide', warning= FALSE}

allTracts <- rbind(tracts19,tracts09)

allTracts.rings <-
  st_join(st_centroid(dplyr::select(allTracts, GEOID, year)), 
          multipleRingBuffer(st_union(SD_Trolley), 14484, 805)) %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(allTracts, GEOID, MedRent, year), 
            by=c("GEOID"="GEOID", "year"="year")) %>%
  st_sf() %>%
  mutate(distance = distance / 1610) 

```

```{r results='hide', warning= FALSE}

allTracts.rings.summary <- allTracts.rings %>%
  dplyr::select(year, distance, MedRent) %>%
  st_drop_geometry() %>%
  group_by(year, distance) %>%
  summarize(Rent=median(MedRent, na.rm=TRUE))

ggplot(data=allTracts.rings.summary, aes(x=distance, y=Rent, group=year)) +
  geom_line(aes(color=year), size=2) +
  geom_point(aes(color=year), size=3.5) +
  scale_color_manual(values = c("#bdc9e1", "016c59")) +
  labs(title = "Rent as function of distance to trolley Stations", subtitle = "Census Tracts") +
  xlab("miles") +
  ylab("Average Rent ($)")
```





